name: status_download
description: A new Flutter application.
version: 6.0.0+6
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.9.8+1
  thumbnails: ^1.0.1
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.0
  flutter_staggered_grid_view:
  path:
  flutter_launcher_icons: ^0.7.4
#  firebase_core: ^0.4.0+1
#  firebase_admob: ^0.5.2
  url_launcher: ^5.4.1
  share: ^0.6.3+5
  simple_permissions:
    git:
      url: https://github.com/prasadsunny1/simple_permissions_upgrade.git
#  permission_handler: ^4.2.0+hotfix.3
  image_gallery_saver: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
    - assets/images/video_loader.gif